# Generated by Django 5.0.6 on 2024-06-10 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Turma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_turma",
                    models.CharField(
                        blank=True, max_length=99, null=True, verbose_name="Turma"
                    ),
                ),
                (
                    "nome_professor",
                    models.CharField(
                        blank=True,
                        max_length=99,
                        null=True,
                        verbose_name="Nome Professor",
                    ),
                ),
                (
                    "id_professor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Id-Professor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Atividades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_atividade",
                    models.CharField(
                        blank=True, max_length=99, null=True, verbose_name="Atividade"
                    ),
                ),
                (
                    "nome_professor",
                    models.CharField(
                        blank=True,
                        max_length=99,
                        null=True,
                        verbose_name="Nome Professor",
                    ),
                ),
                (
                    "nome_turma",
                    models.CharField(
                        blank=True,
                        max_length=99,
                        null=True,
                        verbose_name="Nome Professor",
                    ),
                ),
                (
                    "id_professor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Id-Professor",
                    ),
                ),
                (
                    "id_turma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.turma",
                        verbose_name="Id-Turma",
                    ),
                ),
            ],
        ),
    ]
