# Generated by Django 5.0.6 on 2024-06-10 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_atividades_atividade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atividade",
            name="id_turma",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.turma",
                verbose_name="Id-Turma",
            ),
        ),
    ]
